const f = () => {

    try {
        let a = 0;
        console.log(program)
        console.log("program run succesfully")
        return
    } catch (error) {
        console.log("this is an error")
        console.log(p)
    }
    finally {
        console.log("this code is execute definatally")
    }
}

f()